In [1]:
import nibabel as nib
    
file = 'ADNI_136_S_0429_MR_MPR____N3__Scaled_Br_20070215221039819_S15882_I40392.nii'    #你的nii或者nii.gz文件路径
img = nib.load(file)    
print(img)

<class 'nibabel.nifti1.Nifti1Image'>
data shape (256, 256, 170)
affine: 
[[ 3.43390298e-08  2.59981979e-04 -1.20320256e+00  9.47435837e+01]
 [-2.62488298e-04 -9.93653945e-01 -3.14808767e-04  1.40848755e+02]
 [-1.00322791e+00  2.59983337e-04  4.11838706e-08  1.32038177e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='>'
sizeof_hdr      : 348
data_type       : b''
db_name         : b'136_S_0429'
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 256 256 170   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1.        1.003228  0.993654  1.2032026 1.        1.        1.
 1.       ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 

In [3]:
! pip install imageio

In [7]:
! conda install imageio

Solving environment: done

# All requested packages already installed.



In [11]:
conda install -c conda-forge imageio

Solving environment: done

## Package Plan ##

  environment location: /Applications/anaconda3/envs/AD

  added / updated specs:
    - imageio


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2020.4.5.2 |       hecda079_0         146 KB  conda-forge
    certifi-2020.4.5.2         |   py38h32f6830_0         152 KB  conda-forge
    freetype-2.10.2            |       h8da9a1a_0         874 KB  conda-forge
    imageio-2.8.0              |             py_0         3.1 MB  conda-forge
    jpeg-9d                    |       h0b31af3_0         251 KB  conda-forge
    libblas-3.8.0              |      16_openblas          10 KB  conda-forge
    libcblas-3.8.0             |      16_openblas          10 KB  conda-forge
    libgfortran-4.0.0          |                2         716 KB  conda-forge
    liblapack-3.8.0            |      16_openblas          10 KB  conda-forge
    libop

In [2]:
! pip install -U matplotlib

     |████████████████████████████████| 12.5MB 6.7MB/s eta 0:00:01    |████▍                           | 1.7MB 1.9MB/s eta 0:00:06
  Found existing installation: matplotlib 3.1.1
    Uninstalling matplotlib-3.1.1:
      Successfully uninstalled matplotlib-3.1.1


In [14]:
import os
import numpy as np
import nibabel as nib
import imageio
#import matplotlib
from nibabel.viewers import OrthoSlicer3D
#from matplotlib import pylab as plt
def read_niifile(niifilepath):           #read niifile
    img = nib.load(niifilepath)          #download niifile
    img_fdata = img.get_fdata()          #get niifile data
    return img_fdata
 
def save_fig(niifilepath,savepath):     #save as image
    fdata = read_niifile(niifilepath)   #get data
    (x,y,z) = fdata.shape             #get shape info
    for k in range(z):
        silce = fdata[k,:,:]  
        img_uint8 = silce.astype(np.uint8)
        imageio.imwrite(os.path.join(savepath,'{}.png'.format(k)),img_uint8)
                                        #save as png format(can be jpg as well)
 
if __name__=='__main__':
    niifilepath='ADNI_136_S_0429_MR_MPR____N3__Scaled_Br_20070215221039819_S15882_I40392.nii'
    savepath='ADProject/nipype_tutorial'
    if not os.path.exists(savepath):
        os.makedirs(savepath)
    save_fig(niifilepath,savepath)

In [16]:
from PIL import Image
import numpy as np

In [20]:
im = Image.open('ADProject/nipype_tutorial/140.png')  # open png image
im_array = np.array(im)

In [28]:
np.set_printoptions(threshold=np.inf)

In [29]:
im_array

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0],
       [  0,   0,   0,   0,   0,   0,

In [22]:
im_array.shape

(256, 170)

In [23]:
im_array.dtype

dtype('uint8')